# Generated by Django 4.1 on 2022-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_rename_sgnin_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("placeofpirth", models.CharField(max_length=50)),
                ("ratio", models.CharField(max_length=50)),
                ("dataofbirth", models.CharField(max_length=50)),
                ("namefather", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("mothername", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
