# Generated by Django 4.1 on 2022-08-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_personal_dataofbirth_alter_personal_gender_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Login",),
        migrations.DeleteModel(name="Personal",),
    ]
