# Generated by Django 4.1 on 2022-08-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_personal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("website", models.CharField(max_length=50, null=True)),
                ("message", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="personal",
            name="dataofbirth",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="gender",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="mothername",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="namefather",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="placeofpirth",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="personal",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
