# Generated by Django 4.1 on 2022-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_academy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("placeofbirth", models.CharField(max_length=50, null=True)),
                ("firstwish", models.CharField(max_length=50, null=True)),
                ("ratio", models.CharField(max_length=50, null=True)),
                ("dateofbirth", models.CharField(max_length=50, null=True)),
                ("secondwish", models.CharField(max_length=50, null=True)),
                ("fathersnameandlineage", models.CharField(max_length=50, null=True)),
                ("gender", models.CharField(max_length=50, null=True)),
                ("thirdwish", models.CharField(max_length=50, null=True)),
                ("mothersnameandlineage", models.CharField(max_length=50, null=True)),
                ("maritalstatus", models.CharField(max_length=50, null=True)),
                ("fourthwish", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
