# Generated by Django 4.1 on 2022-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_alter_academy_modified_alter_contact_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="firstwish",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
