# Generated by Django 4.1 on 2022-08-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_alter_academy_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="modified",
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
