# Generated by Django 4.1 on 2022-08-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0023_alter_academy_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academy", options={"verbose_name": "academic information"},
        ),
        migrations.AlterModelOptions(
            name="contact", options={"verbose_name": "contact information"},
        ),
        migrations.AlterModelOptions(name="login", options={"verbose_name": "login"},),
        migrations.AlterModelOptions(
            name="personal",
            options={"ordering": ["name"], "verbose_name": "personal information"},
        ),
        migrations.AlterModelOptions(
            name="wishlist", options={"verbose_name": "determine desire"},
        ),
        migrations.AlterField(
            model_name="academy",
            name="modified",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(default="message"),
        ),
    ]
