# Generated by Django 4.1 on 2022-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_alter_academy_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="certificatedate",
            field=models.CharField(
                max_length=50, null=True, verbose_name="تاريخ الشهادة"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="certificatesource",
            field=models.CharField(
                max_length=50, null=True, verbose_name="مصدر الشهادة"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="elementaryschool",
            field=models.CharField(
                max_length=50, null=True, verbose_name="اسم المدرسة الإبتدائية"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="highschool",
            field=models.CharField(
                max_length=50, null=True, verbose_name="اسم المدرسة الثانوية"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="modified",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="المعدل"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="preparatoryschool",
            field=models.CharField(
                max_length=50, null=True, verbose_name="اسم المدرسة الإعدادية"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(
                max_length=50, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="اسم الدولة"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=50, null=True, verbose_name="رقم الهاتف"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="website",
            field=models.CharField(
                max_length=50, null=True, verbose_name="اسم المدينة"
            ),
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.CharField(max_length=50, verbose_name="البريد الإلكتروني"),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=50, verbose_name="كلمة السر"),
        ),
        migrations.AlterField(
            model_name="personal",
            name="dataofbirth",
            field=models.CharField(
                max_length=50, null=True, verbose_name="تاريخ الولادة "
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                max_length=50,
                null=True,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="mothername",
            field=models.CharField(max_length=50, null=True, verbose_name="اسم الأم"),
        ),
        migrations.AlterField(
            model_name="personal",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="اسم الطالب"),
        ),
        migrations.AlterField(
            model_name="personal",
            name="namefather",
            field=models.CharField(max_length=50, null=True, verbose_name="اسم الأب"),
        ),
        migrations.AlterField(
            model_name="personal",
            name="placeofpirth",
            field=models.CharField(
                max_length=50, null=True, verbose_name="مكان الولادة"
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="ratio",
            field=models.CharField(max_length=50, verbose_name="النسبة"),
        ),
        migrations.AlterField(
            model_name="personal",
            name="status",
            field=models.CharField(
                choices=[("single", "single"), ("married", "married")],
                max_length=50,
                null=True,
                verbose_name="الحالة الإجتماعية",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="dateofbirth",
            field=models.CharField(
                max_length=50, null=True, verbose_name="تاريخ الولادة"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="fathersnameandlineage",
            field=models.CharField(
                max_length=50, null=True, verbose_name="اسم الأب و نسبته"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="firstwish",
            field=models.CharField(
                max_length=50, null=True, verbose_name="الرغبة الأولى"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="fourthwish",
            field=models.CharField(
                max_length=50, null=True, verbose_name="الرغبة الرابعة"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="gender",
            field=models.CharField(max_length=50, null=True, verbose_name="الجنس"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="mothersnameandlineage",
            field=models.CharField(
                max_length=50, null=True, verbose_name="اسم الأم و نسبتها"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="اسم الطالب"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="placeofbirth",
            field=models.CharField(
                max_length=50, null=True, verbose_name="مكان الولادة"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="ratio",
            field=models.CharField(max_length=50, null=True, verbose_name="النسبة"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="secondwish",
            field=models.CharField(
                max_length=50, null=True, verbose_name="الرغبة الثانية"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="status",
            field=models.CharField(
                max_length=50, null=True, verbose_name="الحالة الإجتماعية"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="thirdwish",
            field=models.CharField(
                max_length=50, null=True, verbose_name="الرغبة الثالثة"
            ),
        ),
    ]
