# Generated by Django 4.1 on 2022-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_alter_academy_certificatedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="certificatedate",
            field=models.DateField(null=True, verbose_name="تاريخ الشهادة"),
        ),
        migrations.AlterField(
            model_name="academy",
            name="certificatesource",
            field=models.CharField(
                choices=[
                    ("temporary government", "temporary government"),
                    ("rescue government", "rescue government"),
                    ("local council", "local council"),
                ],
                max_length=50,
                verbose_name="مصدر الشهادة",
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="dataofbirth",
            field=models.DateField(null=True, verbose_name="تاريخ الولادة "),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="dateofbirth",
            field=models.DateField(null=True, verbose_name="تاريخ الولادة"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="firstwish",
            field=models.CharField(
                choices=[
                    ("medicine", "medicine"),
                    ("dentistry", "dentistry"),
                    ("pharmacy", "pharmacy"),
                    ("informatics engineering", "informatics engineering"),
                    ("architecture", "architecture"),
                    ("mechetronics engineering", "mechetronics engineering"),
                    ("trade and economy", "trade and economy"),
                ],
                max_length=50,
                null=True,
                verbose_name="الرغبة الأولى",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="fourthwish",
            field=models.CharField(
                choices=[
                    ("medicine", "medicine"),
                    ("dentistry", "dentistry"),
                    ("pharmacy", "pharmacy"),
                    ("informatics engineering", "informatics engineering"),
                    ("architecture", "architecture"),
                    ("mechetronics engineering", "mechetronics engineering"),
                    ("trade and economy", "trade and economy"),
                ],
                max_length=50,
                null=True,
                verbose_name="الرغبة الرابعة",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                max_length=50,
                null=True,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="secondwish",
            field=models.CharField(
                choices=[
                    ("medicine", "medicine"),
                    ("dentistry", "dentistry"),
                    ("pharmacy", "pharmacy"),
                    ("informatics engineering", "informatics engineering"),
                    ("architecture", "architecture"),
                    ("mechetronics engineering", "mechetronics engineering"),
                    ("trade and economy", "trade and economy"),
                ],
                max_length=50,
                null=True,
                verbose_name="الرغبة الثانية",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="thirdwish",
            field=models.CharField(
                choices=[
                    ("medicine", "medicine"),
                    ("dentistry", "dentistry"),
                    ("pharmacy", "pharmacy"),
                    ("informatics engineering", "informatics engineering"),
                    ("architecture", "architecture"),
                    ("mechetronics engineering", "mechetronics engineering"),
                    ("trade and economy", "trade and economy"),
                ],
                max_length=50,
                null=True,
                verbose_name="الرغبة الثالثة",
            ),
        ),
    ]
