# Generated by Django 4.1 on 2022-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0027_alter_academy_certificatedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="certificatedate",
            field=models.DateField(
                max_length=50, null=True, verbose_name="تاريخ الشهادة"
            ),
        ),
    ]
