# Generated by Django 4.1 on 2022-08-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_rename_decument_document_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='certificatesource',
            field=models.CharField(max_length=50, verbose_name='مصدر الشهادة'),
        ),
        migrations.AlterField(
            model_name='document',
            name='imgcer',
            field=models.ImageField(upload_to='certificatePhotos/%y/%m/%d', verbose_name='صورة الشهادة'),
        ),
        migrations.AlterField(
            model_name='document',
            name='imgid',
            field=models.ImageField(upload_to='idPhotos/%y/%m/%d', verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='document',
            name='imgper',
            field=models.ImageField(upload_to='personalPhoto/%y/%m/%d', verbose_name='صورة شخصية'),
        ),
    ]
