# Generated by Django 4.1 on 2022-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_uploadimage_alter_academy_certificatesource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imgper', models.ImageField(upload_to='images')),
            ],
        ),
    ]
